version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - '5173:5173'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - '8080:8080'
    environment:
      OLLAMA_HOST: http://ollama:11434
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - '11434:11434'
    entrypoint: ["/usr/bin/env", "bash", "/entrypoint.sh"]
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:11434']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
