version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - '3000:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - '8080:8080'
    environment:
      OLLAMA_HOST: http://ollama:11434
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      ollama:
        condition: service_started
    networks:
      - app-network

  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - '11434:11434'
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
